Repository nolanhacky/HackyHacktober, pull requests merged in 2021-10, with the labels that each got.

#2 Data extraction from exchange api
  extract_api.py
Labels: enhancement

#6 Tideman Election System
  cs50/pset3/tideman/tideman
  cs50/pset3/tideman/tideman.c
  cs50/readability/readability
  cs50/readability/readability.c
  cs50/scrabble/scrabble
  cs50/scrabble/scrabble.c
Labels: hard

#7 Plurality Problem CS50
  cs50/pset2/readability/readability
  cs50/pset2/readability/readability.c
  cs50/pset2/scrabble/scrabble
  cs50/pset2/scrabble/scrabble.c
  cs50/pset2/subsitution/substitution
  cs50/pset2/subsitution/substitution.c
  cs50/pset3/plurality/plurality
  cs50/pset3/plurality/plurality.c
Labels: good first issue

#9 Lab3 of CS50
  cs50/pset3/lab3/answers.txt
  cs50/pset3/lab3/random10000.txt
  cs50/pset3/lab3/random5000.txt
  cs50/pset3/lab3/random50000.txt
  cs50/pset3/lab3/reversed10000.txt
  cs50/pset3/lab3/reversed5000.txt
  cs50/pset3/lab3/reversed50000.txt
  cs50/pset3/lab3/sort1
  cs50/pset3/lab3/sort2
  cs50/pset3/lab3/sort3
  cs50/pset3/lab3/sorted10000.txt
  cs50/pset3/lab3/sorted5000.txt
  cs50/pset3/lab3/sorted50000.txt
Labels: good first issue
